---
pacifica_enabled_services:
  - uniqueid
  - archiveinterface
  - cartd_frontend
  - cartd_backend
  - ingest_frontend
  - ingest_backend
  - notify_frontend
  - notify_backend


drupal_compose_project_options_dev: "{% if keep_vcs is defined and ( keep_vcs | bool ) %}--keep-vcs{% endif %}"
drupal_compose_project_package_version: "{% if keep_vcs is defined and ( keep_vcs | bool ) %}8.x-vcs-dev{% else %}0.1.0{% endif %}"
drupalvm_config:
  composer_version: '1.10.16'
  hostname_configure: false
  firewall_enabled: false
  drupal_build_makefile: false
  drupal_composer_project_package: "pacifica/drupal-project:{{ drupal_compose_project_package_version }}"
  drupal_install_profile: pacifica
  drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction {{ drupal_compose_project_options_dev }}"
  installed_extras:
    - drush
    - redis
    - nodejs
    - solr
    - mailhog
    - memcached
    - pimpmylog
    - varnish
  extra_packages:
    - rsync
    - sqlite
    - vim
    - cronie
    - crontabs
  nodejs_version: '12.x'
  php_apc_shm_size: "1024M"
  php_memory_limit: "4096M"
  php_upload_max_filesize: "4096M"
  php_post_max_size: "4096M"
  solr_version: "7.7.2"
  solr_xms: "1024M"
  solr_xmx: "2048M"
  mysql_max_connections: 200
  mysql_max_allowed_packet: 2048M
  mysql_query_cache_limit: 1024M
  mysql_query_cache_size: 256M
  mysql_query_cache_type: 1
  mysql_innodb_buffer_pool_size: 128M
  mysql_innodb_flush_method: O_DIRECT
  drupal_site_name: Pacifica Site
  drupal_composer_dependencies:
    - '"symfony/event-dispatcher:4.3.11 as 3.4.41"'
    - "drupal/key_auth"
    - "drupal/restui"
  drupal_enable_modules:
    - "restui"
    - "basic_auth"
    - "key_auth"
  mysql_databases:
    - name: "drupal"
      encoding: utf8mb4
      collation: utf8mb4_general_ci
    - name: "cartd"
      encoding: utf8mb4
      collation: utf8mb4_general_ci
    - name: "ingest"
      encoding: utf8mb4
      collation: utf8mb4_general_ci
    - name: "uniqueid"
      encoding: utf8mb4
      collation: utf8mb4_general_ci
    - name: "notify"
      encoding: utf8mb4
      collation: utf8mb4_general_ci
  mysql_users:
    - name: "drupal"
      host: "%"
      password: "drupal"
      priv: "drupal.*:ALL"
    - name: "cartd"
      host: "%"
      password: "cartd"
      priv: "cartd.*:ALL"
    - name: "ingest"
      host: "%"
      password: "ingest"
      priv: "ingest.*:ALL"
    - name: "notify"
      host: "%"
      password: "notify"
      priv: "notify.*:ALL"
    - name: "uniqueid"
      host: "%"
      password: "uniqueid"
      priv: "uniqueid.*:ALL"
  drupal_domain: localhost
  extra_default_ssl_aliases: localhost.localdomain
  extra_default_aliases: localhost.localdomain
  apache_secure_headers: |
    Header unset X-Generator
  apache_redirect_https: |
    RewriteEngine On
    RewriteCond %{HTTPS} !=on
    RewriteRule ^/?(.*) https://%{SERVER_NAME}/$1 [R,L]
  apache_ssl_cipher_suite: "EECDH:!RC4:!3des:!SHA"
  apache_ssl_protocol: "-all +TLSv1.2"
  apache_vhosts_ssl:
    - servername: "{% raw %}{{ drupal_domain }}{% endraw %}"
      serveralias: "{% raw %}{{ extra_default_ssl_aliases | default('') }}{% endraw %}"
      documentroot: "{% raw %}{{ drupal_core_path }}{% endraw %}"
      certificate_file: /etc/pki/tls/certs/localhost.localdomain.crt
      certificate_key_file: /etc/pki/tls/private/localhost.localdomain.pem
      certificate_chain_file: /etc/pki/tls/certs/pacifica_chain.io.crt
      extra_parameters: "{% raw %}{{ apache_secure_headers }}{{ apache_vhost_php_fpm_parameters }}{% endraw %}"
  apache_vhosts:
    - servername: "{% raw %}{{ drupal_domain }}{% endraw %}"
      serveralias: "{% raw %}{{ extra_default_aliases | default('') }}{% endraw %}"
      documentroot: "{% raw %}{{ drupal_core_path }}{% endraw %}"
      extra_parameters: "{% raw %}{{ apache_redirect_https }}{% endraw %}"
  apache_global_vhost_settings: |
    ServerTokens Prod
