---
- hosts: local
  tasks:
    - name: Setup PostgreSQL
      include_role:
        name: geerlingguy.postgresql
    - name: Setup Redis
      include_role:
        name: geerlingguy.redis
    - name: Setup PostgreSQL
      include_role:
        name: pacifica.ansible_pacifica

