---
- src: pacifica.ansible_drupalsolr
  version: v1.0.0
- src: pacifica.ansible_drupalvm
  version: v0.3.0
- src: pacifica.ansible_pacifica
  version: v0.5.0
- src: pacifica.ansible_certinfra
  version: v0.2.1
- src: pacifica.ansible_keycloak
  version: v0.2.0
- src: pacifica.drupal_keycloak
  version: v0.4.1
