---
- name: Setup DrupalVM
  hosts: local
  pre_tasks:
    - name: Install Packages
      package:
        name:
          - openssh-server
          - openssh-clients
          - rsyslog
    - name: Start Enable SSHD
      service:
        name: sshd
        enabled: yes
        state: started
    - name: Start Enable rsyslog
      service:
        name: rsyslog
        enabled: yes
        state: started
  roles:
    - role: pacifica.ansible_drupalvm
    - role: pacifica.ansible_certinfra
    - role: pacifica.ansible_keycloak
  post_tasks:
    - name: Create DrupalVM Config
      copy:
        content: "{{ drupalvm_config | to_nice_yaml }}"
        dest: "{{ drupalvm_dir }}/local.config.yml"
    - name: Create System Service for Postfix IPv6 issue
      copy:
        content: |
          [Unit]
          Description=Postfix IPv6 Hosts Fix
          Before=postfix.service
          [Service]
          ExecStart=/usr/local/bin/ansible-playbook /etc/ansible/pacifica-vm/hosts-play.yml
          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/postfix-hosts-fix.service"
        owner: root
        group: root
        mode: 0644
    - name: reload systemd
      command: systemctl daemon-reload
    - name: enable postfix hosts fix
      service:
        name: postfix-hosts-fix
        enabled: true
        state: started
